<a href="https://colab.research.google.com/github/Mohammadyasin123/houseprediction1/blob/main/houseprediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1.Import library

In [ ]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.pipeline import make_pipeline
from sklearn.compose import make_column_transformer

In [ ]:
data=pd.read_csv("/content/Bengaluru_House_Data.csv")

In [ ]:
data

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00
...,...,...,...,...,...,...,...,...,...
13315,Built-up Area,Ready To Move,Whitefield,5 Bedroom,ArsiaEx,3453,4.0,0.0,231.00
13316,Super built-up Area,Ready To Move,Richards Town,4 BHK,NaN,3600,5.0,NaN,400.00
13317,Built-up Area,Ready To Move,Raja Rajeshwari Nagar,2 BHK,Mahla T,1141,2.0,1.0,60.00
13318,Super built-up Area,18-Jun,Padmanabhanagar,4 BHK,SollyCl,4689,4.0,1.0,488.00
13319,Super built-up Area,Ready To Move,Doddathoguru,1 BHK,NaN,550,1.0,1.0,17.00

removing unwanted columns

In [ ]:
data.drop(columns=['area_type','availability','society'],inplace=True)

In [ ]:
data

                       location       size total_sqft  bath  balcony   price
0      Electronic City Phase II      2 BHK       1056   2.0      1.0   39.07
1              Chikka Tirupathi  4 Bedroom       2600   5.0      3.0  120.00
2                   Uttarahalli      3 BHK       1440   2.0      3.0   62.00
3            Lingadheeranahalli      3 BHK       1521   3.0      1.0   95.00
4                      Kothanur      2 BHK       1200   2.0      1.0   51.00
...                         ...        ...        ...   ...      ...     ...
13315                Whitefield  5 Bedroom       3453   4.0      0.0  231.00
13316             Richards Town      4 BHK       3600   5.0      NaN  400.00
13317     Raja Rajeshwari Nagar      2 BHK       1141   2.0      1.0   60.00
13318           Padmanabhanagar      4 BHK       4689   4.0      1.0  488.00
13319              Doddathoguru      1 BHK        550   1.0      1.0   17.00

[13320 rows x 6 columns]

removing **zero , clean tha data , null value , missing value drop

In [ ]:
data.dropna(inplace=True)

In [ ]:
data

                       location       size total_sqft  bath  balcony   price
0      Electronic City Phase II      2 BHK       1056   2.0      1.0   39.07
1              Chikka Tirupathi  4 Bedroom       2600   5.0      3.0  120.00
2                   Uttarahalli      3 BHK       1440   2.0      3.0   62.00
3            Lingadheeranahalli      3 BHK       1521   3.0      1.0   95.00
4                      Kothanur      2 BHK       1200   2.0      1.0   51.00
...                         ...        ...        ...   ...      ...     ...
13314         Green Glen Layout      3 BHK       1715   3.0      3.0  112.00
13315                Whitefield  5 Bedroom       3453   4.0      0.0  231.00
13317     Raja Rajeshwari Nagar      2 BHK       1141   2.0      1.0   60.00
13318           Padmanabhanagar      4 BHK       4689   4.0      1.0  488.00
13319              Doddathoguru      1 BHK        550   1.0      1.0   17.00

[12710 rows x 6 columns]

In [ ]:
data.location.value_counts()

location
Whitefield         514
Sarjapur  Road     372
Electronic City    300
Kanakpura Road     261
Thanisandra        231
                  ...
Gulakamale           1
Duddanahalli         1
Doddanakunte         1
Jogupalya            1
Abshot Layout        1
Name: count, Length: 1265, dtype: int64

removing leading space

In [ ]:
data['location']= data['location'].apply(lambda x:x.strip())

In [ ]:
data.location.value_counts()

location
Whitefield             515
Sarjapur  Road         372
Electronic City        302
Kanakpura Road         261
Thanisandra            234
                      ...
Mango Garden Layout      1
CHIKKATIRUPATHI          1
Jaladarsini Layout       1
Madanayakahalli          1
sapthagiri Layout        1
Name: count, Length: 1254, dtype: int64

data blancing

In [ ]:
locations_starts = data.groupby('location')['location'].agg('count').sort_values(ascending=False)

In [ ]:
locations_less_then_10_enteries=locations_starts[locations_starts<=10]

In [ ]:
locations_less_then_10_enteries

location
Basapura                   10
Gunjur Palya               10
Dairy Circle               10
HAL 2nd Stage              10
Kalkere                    10
                           ..
mvj engineering college     1
manyata tech park           1
manyata                     1
kg halli jalhalli west      1
kanakapura road             1
Name: location, Length: 1017, dtype: int64

In [ ]:
#replacing less than 10
data['location']= data['location'].apply(lambda x:'others'if x in locations_less_then_10_enteries else x )

In [ ]:
data['location'].value_counts()

location
others              2739
Whitefield           515
Sarjapur  Road       372
Electronic City      302
Kanakpura Road       261
                    ...
Marsur                11
Karuna Nagar          11
Prithvi Layout        11
Doddaballapur         11
Thyagaraja Nagar      11
Name: count, Length: 238, dtype: int64

In [ ]:
data
#location cleanup done

                       location       size total_sqft  bath  balcony   price
0      Electronic City Phase II      2 BHK       1056   2.0      1.0   39.07
1              Chikka Tirupathi  4 Bedroom       2600   5.0      3.0  120.00
2                   Uttarahalli      3 BHK       1440   2.0      3.0   62.00
3            Lingadheeranahalli      3 BHK       1521   3.0      1.0   95.00
4                      Kothanur      2 BHK       1200   2.0      1.0   51.00
...                         ...        ...        ...   ...      ...     ...
13314         Green Glen Layout      3 BHK       1715   3.0      3.0  112.00
13315                Whitefield  5 Bedroom       3453   4.0      0.0  231.00
13317     Raja Rajeshwari Nagar      2 BHK       1141   2.0      1.0   60.00
13318           Padmanabhanagar      4 BHK       4689   4.0      1.0  488.00
13319              Doddathoguru      1 BHK        550   1.0      1.0   17.00

[12710 rows x 6 columns]

In [ ]:
data['size'].unique()

array(['2 BHK', '4 Bedroom', '3 BHK', '3 Bedroom', '1 BHK', '1 RK',
       '4 BHK', '1 Bedroom', '2 Bedroom', '6 Bedroom', '8 Bedroom',
       '7 Bedroom', '5 BHK', '7 BHK', '6 BHK', '5 Bedroom', '11 BHK',
       '9 BHK', '9 Bedroom', '27 BHK', '11 Bedroom', '43 Bedroom',
       '14 BHK', '8 BHK', '12 Bedroom', '10 Bedroom', '13 BHK'],
      dtype=object)

In [ ]:
#taking only numeric value so that we can not depend size columns and new colums bedroom is made
data['bedrooms']=data['size'].apply(lambda x:int(x.split(' ')[0]))

In [ ]:
data.head()

,location,size,total_sqft,bath,balcony,price,bedrooms
0,Electronic City Phase II,2 BHK,1056,2.0,1.0,39.07,2
1,Chikka Tirupathi,4 Bedroom,2600,5.0,3.0,120.00,4
2,Uttarahalli,3 BHK,1440,2.0,3.0,62.00,3
3,Lingadheeranahalli,3 BHK,1521,3.0,1.0,95.00,3
4,Kothanur,2 BHK,1200,2.0,1.0,51.00,2

In [ ]:
#what are the unique value
data.total_sqft.unique()

array(['1056', '2600', '1440', ..., '1133 - 1384', '774', '4689'],
      dtype=object)

In [ ]:
def clean(sqft):
  tokens = sqft.split('-')
  if len(tokens)==2:
    return (float(tokens[0]) + float(tokens[1])) / 2
  else:
    try:
      return float(sqft)
    except ValueError:
      return None

In [ ]:
data['total_sqft']=data['total_sqft'].apply(clean)

AttributeError: 'float' object has no attribute 'split'

In [ ]:
data['total_sqft'].unique()

array([1056. , 2600. , 1440. , ..., 1258.5,  774. , 4689. ])

In [ ]:
data.dropna(inplace=True)

In [ ]:
data.describe()

,total_sqft,bath,balcony,price,bedrooms,sqft_per_bed
count,12668.000000,12668.000000,12668.000000,12668.000000,12668.000000,12668.000000
mean,1511.835167,2.616277,1.585649,105.952648,2.736422,570.060291
std,1162.097276,1.223882,0.816758,131.813137,1.202643,380.298999
min,5.000000,1.000000,0.000000,8.000000,1.000000,0.714286
25%,1100.000000,2.000000,1.000000,49.015000,2.000000,473.333333
50%,1260.000000,2.000000,2.000000,70.000000,3.000000,550.000000
75%,1640.000000,3.000000,2.000000,115.000000,3.000000,622.500000
max,52272.000000,40.000000,3.000000,2912.000000,43.000000,26136.000000

In [ ]:
#finding how much per sqft per bedrooms
data['sqft_per_bed']=data['total_sqft']/data['bedrooms']

/tmp/ipython-input-2852448796.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['sqft_per_bed']=data['total_sqft']/data['bedrooms']

In [ ]:
data.sqft_per_bed.describe()

count    12668.000000
mean       570.060291
std        380.298999
min          0.714286
25%        473.333333
50%        550.000000
75%        622.500000
max      26136.000000
Name: sqft_per_bed, dtype: float64

In [ ]:
#removing less than 300
data=data[data['sqft_per_bed']>=300]

In [ ]:
data

,location,size,total_sqft,bath,balcony,price,bedrooms,sqft_per_bed
0,Electronic City Phase II,2 BHK,1056.0,2.0,1.0,39.07,2,528.000000
1,Chikka Tirupathi,4 Bedroom,2600.0,5.0,3.0,120.00,4,650.000000
2,Uttarahalli,3 BHK,1440.0,2.0,3.0,62.00,3,480.000000
3,Lingadheeranahalli,3 BHK,1521.0,3.0,1.0,95.00,3,507.000000
4,Kothanur,2 BHK,1200.0,2.0,1.0,51.00,2,600.000000
...,...,...,...,...,...,...,...,...
13314,Green Glen Layout,3 BHK,1715.0,3.0,3.0,112.00,3,571.666667
13315,Whitefield,5 Bedroom,3453.0,4.0,0.0,231.00,5,690.600000
13317,Raja Rajeshwari Nagar,2 BHK,1141.0,2.0,1.0,60.00,2,570.500000
13318,Padmanabhanagar,4 BHK,4689.0,4.0,1.0,488.00,4,1172.250000
13319,Doddathoguru,1 BHK,550.0,1.0,1.0,17.00,1,550.000000

In [ ]:
data['price_per_sqft']=data['price']*100000/data['total_sqft']

/tmp/ipython-input-3782827614.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['price_per_sqft']=data['price']*100000/data['total_sqft']

In [ ]:
data.price_per_sqft.describe()

count     12013.000000
mean       6206.082347
std        3985.518807
min         267.829813
25%        4199.363057
50%        5252.525253
75%        6823.529412
max      176470.588235
Name: price_per_sqft, dtype: float64

In [ ]:
data3 = data[data['price_per_sqft'] >= 2000]

In [ ]:
data3 = data3.drop(columns= ['size' ,'sqft_per_bed','price_per_sqft'])

In [ ]:
data3

,location,size,total_sqft,bath,balcony,price,bedrooms,sqft_per_bed,price_per_sqft
0,Electronic City Phase II,2 BHK,1056.0,2.0,1.0,39.07,2,528.000000,3699.810606
1,Chikka Tirupathi,4 Bedroom,2600.0,5.0,3.0,120.00,4,650.000000,4615.384615
2,Uttarahalli,3 BHK,1440.0,2.0,3.0,62.00,3,480.000000,4305.555556
3,Lingadheeranahalli,3 BHK,1521.0,3.0,1.0,95.00,3,507.000000,6245.890861
4,Kothanur,2 BHK,1200.0,2.0,1.0,51.00,2,600.000000,4250.000000
...,...,...,...,...,...,...,...,...,...
13314,Green Glen Layout,3 BHK,1715.0,3.0,3.0,112.00,3,571.666667,6530.612245
13315,Whitefield,5 Bedroom,3453.0,4.0,0.0,231.00,5,690.600000,6689.834926
13317,Raja Rajeshwari Nagar,2 BHK,1141.0,2.0,1.0,60.00,2,570.500000,5258.545136
13318,Padmanabhanagar,4 BHK,4689.0,4.0,1.0,488.00,4,1172.250000,10407.336319
13319,Doddathoguru,1 BHK,550.0,1.0,1.0,17.00,1,550.000000,3090.909091

In [ ]:
col_trans=make_column_transformer((OneHotEncoder(sparse_output=False),['location']), remainder ='passthrough')

In [ ]:
lr = LinearRegression()

In [ ]:
scaler = StandardScaler()

In [ ]:
model=make_pipeline(col_trans, scaler, lr)

In [ ]:
data_input=data3.drop(columns =['price'])
data_output=data3['price']

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(data_input,data_output,test_size=0.2)

In [ ]:
model.fit(x_train,y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/compose/_column_transformer.py:1667: FutureWarning:
The format of the columns of the 'remainder' transformer in ColumnTransformer.transformers_ will change in version 1.7 to match the format of the other transformers.
At the moment the remainder columns are stored as indices (of type int). With the same ColumnTransformer configuration, in the future they will be stored as column names (of type str).
To use the new behavior now and suppress this warning, use ColumnTransformer(force_int_remainder_cols=False).

  warnings.warn(

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(sparse_output=False),
                                                  ['location'])])),
                ('standardscaler', StandardScaler()),
                ('linearregression', LinearRegression())])

In [ ]:
model.score(x_test,y_test)

0.8590893926941571

In [ ]:
new_data_point = pd.DataFrame([['Electronic City Phase II', 1056.0, 2.0, 1.0, 2]], columns=['location','total_sqft','bath','balcony','bedrooms'])

In [ ]:
predicted_price = model.predict(new_data_point)
print(f"The predicted price for the new data point is: {predicted_price[0]:.2f} Lakhs")

The predicted price for the new data point is: 34.44 Lakhs

In [ ]:
predicted_price = model.predict(new_data_point)
print(f"The predicted price for the new data point is: {predicted_price[0]:.2f} Lakhs")

The predicted price for the new data point is: 34.44 Lakhs